### ISSUE TITLE
Phương pháp trượt

### ISSUE THREAD

**Issue by thientt03** [thientt03/SE15.01#18]

**Comment by thientt03** [comment]
Sử dụng mô phỏng sự trượt của 1 mảnh quay quanh 1 mảnh đứng yên không bao h không tiếp xúc. NFP được xác định bởi đường đi được tạo bởi quỹ đạo trong khi nó trượt quanh mảnh đứng yên

**Comment by jungen12** [comment]
phát hiện các chuyển động chính xác mà B phải thực hiện để đi qua A để quay trở lại vị trí ban đầu của nó. Đây là một quy trình lặp đi lặp lại với mỗi bước dịch tạo ra một cạnh của đa giác không vừa vặn. Điều này có thể được chia nhỏ hơn nữa thành các phần con sau đây sẽ lần lượt được thảo luận: phát hiện các cạnh chạm, tạo vectơ dịch tiềm năng, tìm bản dịch khả thi, cắt bớt bản dịch khả thi và cuối cùng, áp dụng tính khả thi
