### ISSUE TITLE
No-Fit-Polygon

### ISSUE THREAD

**Issue by thientt03** [thientt03/SE15.01#3]
- Định nghĩa
- Công thức
- Cách thức vận hành

**Comment by thientt03** [comment]
Định nghĩa: Là tập hợp tất cả các vị trí sắp xếp khả thi của 1 đa giác so với đa giác khác. Nó chuyển đổi quá trình xác minh chồng chéo giữa 2 đa giác ----> xác minh chồng chéo giữa 1 đa giác và 1 đỉnh

**Comment by thientt03** [comment]
![image](https://user-images.githubusercontent.com/47145219/103479874-3cfcc900-4e03-11eb-92a1-2e5c22cd99ae.png)

**Comment by thientt03** [comment]
mô phỏng sự trượt của 1 mảnh quay quanh 1 mảnh đứng yên luôn tiếp xúc. NFP được xác định bởi đg đi tạo bởi các điểm tham chiếu của mảnh quỹ đạo trong khi nó trượt quanh mảnh đứng yên

**Comment by thientt03** [comment]
![image](https://user-images.githubusercontent.com/47145219/103479956-c3190f80-4e03-11eb-8840-9e539e098a79.png)

**Comment by NMinhDuc99** [comment]
![no-fit-polygon-NFP](https://user-images.githubusercontent.com/68629665/103480600-ca421c80-4e07-11eb-9ab9-899a02b02afb.png)
