### ISSUE TITLE
Cách sử dụng nesting trong thực tế

### ISSUE THREAD

**Issue by thientt03** [thientt03/SE15.01#9]

**Comment by quoccuong1998ls** [comment]
sử dụng tích hợp vào máy cắt vật liệu CNC

**Comment by DinhDungNguyen** [comment]
Sử dụng nesting trong thực tế thường được áp dụng trong công nghiệp 4.0
Các nhà sản xuất cần lên bản thảo thiết kế, đưa ra yêu cầu đối với sản phẩm. Công nghệ nesting giúp tối ưu hóa nguyên vật liệu đồng thời đưa ra bản cắt tối ưu nhất cho từng phôi vật liệu. Công nghệ nesting có năng suất và chất lượng hơn hẳn so với thủ công, qua đó cũng giải quyết vấn đề khan hiếm nhân công trong nhiều ngành công nghiệp.

**Comment by DungNgDinh** [comment]
Sử dụng nesting trong thực tế thường được áp dụng trong công nghiệp 4.0
Các nhà sản xuất cần lên bản thảo thiết kế, đưa ra yêu cầu đối với sản phẩm. Công nghệ nesting giúp tối ưu hóa nguyên vật liệu đồng thời đưa ra bản cắt tối ưu nhất cho từng phôi vật liệu. Công nghệ nesting có năng suất và chất lượng hơn hẳn so với thủ công, qua đó cũng giải quyết vấn đề khan hiếm nhân công trong nhiều ngành công nghiệp.
